version: "2"
run:
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - nilerr
    - revive
    - staticcheck
  settings:
    gosec:
      excludes:
        - G304
  exclusions:
    generated: lax
    paths:
      - vendor
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor
